### ISSUE TITLE
Issues with old iOS versions in simulator

### ISSUE THREAD

**Issue by bassosimone** [TheTorProject/ooniprobe-ios#105]
With a47f53661973281c8295a3057e7445599dca2545 as the tip, I've noticed the following issues while testing with simulators (note: no issues on real iPhone 5s with iOS 10.2):

- The "all set / tutto pronto" button of the on-boarding procedure is not clickable (iOS 8.4)
- Results are not visualised for any test (iOS 8.4 and 9.3)

Cc: @hellais @lorenzoPrimi

**Comment by lorenzoPrimi** [comment]
https://github.com/TheTorProject/ooniprobe-ios/pull/98/commits/72c2a3c98a61eaf38ec1d75f0114cd2fb52518e6 should fix the first issue, along with other graphic bugs

**Comment by hellais** [comment]
This branch implements a fix for the second bug: https://github.com/TheTorProject/ooni-wui/pull/43

**Comment by hellais** [comment]
This is fixed.
