### ISSUE TITLE
iOS 8.4: missing encoding in results view

### ISSUE THREAD

**Issue by bassosimone** [TheTorProject/ooniprobe-ios#106]
@bassosimone commented on [Thu Mar 16 2017](https://github.com/TheTorProject/ooni-wui/issues/44)

I have noticed, using ooniprobe-ios in italian, that the encoding is not correctly set, as showed by the following screenshot:

![screen shot 2017-03-16 at 17 57 04](https://cloud.githubusercontent.com/assets/337298/24008635/72e0c716-0a72-11e7-85fb-15f140c34a2b.png)

(and, yes, damn, I left the mouse pointer over the window and forgot that the emulator allows to take pictures much more efficiently than capturing all screen and cropping.)

---

@hellais commented on [Thu Mar 16 2017](https://github.com/TheTorProject/ooni-wui/issues/44#issuecomment-287126023)

I suspect this may have to do with how the pages are serve by ooniprobe-ios (and possibly also ooniprobe-android).

The meta tag is set properly and on desktop it works as expected:
![screen shot 2017-03-16 at 17 08 28 0000](https://cloud.githubusercontent.com/assets/424620/24008932/35942030-0a6b-11e7-9a77-e111f143369b.png)

---

@bassosimone commented on [Thu Mar 16 2017](https://github.com/TheTorProject/ooni-wui/issues/44#issuecomment-287126621)

Update: I see the problem *only* with iOS 8.4.

**Comment by hellais** [comment]
So this seems like an issue in how the javascript files are served by iOS. It looks like they are interpreted as if the encoding is ascii, while it's actually utf-8.

See:
![screen shot 2017-03-16 at 17 28 13 0000](https://cloud.githubusercontent.com/assets/424620/24009858/15b9b1f0-0a6e-11e7-8c10-395c54c97ed9.png)

**Comment by hellais** [comment]
I think I found a way to fix this on the web UI side of things. It doesn't require any code changes, but only changes to the build script.
See: https://github.com/TheTorProject/ooni-wui/commit/33bf8f0ace1829e273c132ac154146c2f633001b

I updated the same release tag (rc.6) to include this fix. Can you try downloading and updating?

**Comment by hellais** [comment]
This is fixed.
