### ISSUE TITLE
Green dot near specific test result not shown in all cases

### ISSUE THREAD

**Issue by bassosimone** [TheTorProject/ooniprobe-ios#107]
Steps to reproduce:

- open the simulator (I'm using iOS 10.2 in this case)
- start http-invalid-request-line and web-connectivity
- when http-invalid-request-line terminates, the green dot appears; go to results as soon as you see the green dot (when in general web-connectivity should still be running)
- return back to the start tests view
- wait for web-connectivity to terminate
- you shall see a green dot in the menu but not green dot when you go in results over the just-terminated web-connectivity test

Maybe we can defer this after 1.1.3, given that it does not seem to me to be a blocker.

**Comment by bassosimone** [comment]
@lorenzoPrimi: I see that you pushed commits for fixing this issue. Can we consider it fixed for good, or is there more work to be done to have it fully addressed?

**Comment by lorenzoPrimi** [comment]
Fixed and tested
