### ISSUE TITLE
Typographical issues

### ISSUE THREAD

**Issue by gmcgath** [TheTorProject/ooniprobe-ios#109]
These are in Localizable Strings (Base):

"risks_text_5" = "Since ooniprobe is an investigatory tool and as such, may pose some risks.";
Either the word "Since" should be removed, or "and as such, may" should be changed to "it."

laws_text_6 is defined twice. Both definitions are identical, so this is harmless but should be fixed.

"set_up_sharing" = "Setup Sharing";
Should that be "Set up Sharing"?

risks_text_5 is the important one, since new users see it.

**Comment by hellais** [comment]
@agrabeli what are your thoughts on this?

**Comment by hellais** [comment]
@gmcgath we are working on a revamped OONI Probe mobile and are going to be changing all the copy in there, so this will be solved in 2.0.0.
