### ISSUE TITLE
Links word oddly inside of Twitter

### ISSUE THREAD

**Issue by bassosimone** [TheTorProject/ooniprobe-ios#129]
I [tweeted](https://twitter.com/bassosimone/status/912314622908256257) links to run.ooni.io. When I clicked on them on Twitter on a device the app was not opened, and instead I was directed on run.ooni.io. There, I could click on a button to run the test successfully.

I guess this is okay for a first release, because the functionality is there. What is a bit annoying is that you need to click twice. To confirm you're sure you want to leave Twitter and to confirm that you want to allow Twitter to open ooniprobe.

**Comment by lorenzoPrimi** [comment]
That do you mean "app was not opened" ?
Never at all or killed manually?

**Comment by bassosimone** [comment]
> That do you mean "app was not opened" ?
> Never at all or killed manually?

I mean that the result of clicking on such link from Twitter is not that the app is opened to run the test, rather that Twitter's browser is opened and goes on run.ooni.io for the selected URL.

**Comment by lorenzoPrimi** [comment]
Ok this is the fix that @hellais developed. He will explain it to you.

**Comment by bassosimone** [comment]
Yeah, perhaps this is not an app issue, but an issue with run.ooni.io

**Comment by hellais** [comment]
I actually had fixed this but then I lost the commit when I did a refactor. I re-added the fix.

**Comment by hellais** [comment]
It should now be deployed.

**Comment by bassosimone** [comment]
> I actually had fixed this but then I lost the commit when I did a refactor. I re-added the fix.
> It should now be deployed.

ACK, I can probably test again later.

**Comment by hellais** [comment]
It only works when clicking on the card. @bassosimone reported that this is fixed.

**Comment by bassosimone** [comment]
Thanks!
