### ISSUE TITLE
Running run.ooni.io test does not change the app view

### ISSUE THREAD

**Issue by bassosimone** [TheTorProject/ooniprobe-ios#130]
As I wrote on slack (text slightly edited):

> if I have the app already open, then I click on a link, after I select run, I stay in the app view in which I was, which, in many cases, it's odd. Like, currently I was seeing the results of the previous test and the new test is running but I don't see any indication of it

I would say that probably the view should be changed to give an indication that the test is running. I mean: I was confused that I was still seeing the results of the previous test and not the running of the new test that I just submitted to ooniprobe by clicking on a run.ooni.io link and then on the "run" button.

**Comment by lorenzoPrimi** [comment]
This will be fixed when we switch to tabbed apps
