### ISSUE TITLE
The run.ooni.io view persists if not dismissed

### ISSUE THREAD

**Issue by bassosimone** [TheTorProject/ooniprobe-ios#132]
As I wrote on Slack:

> if I click on a link, then I don't run a test, then I click on a second link, I still see the running screen of the former test, rather than the running screen of the second one, as I would expect

**Comment by hellais** [comment]
I am not sure I fully understand the issue. Can you provide steps to reproduce?

**Comment by bassosimone** [comment]
> I am not sure I fully understand the issue

Ouch.

> Can you provide steps to reproduce?

- Click on a run.ooni.io link.

- Do not run the test and close the app.

- Click on another run.ooni.io link.

- You would expect to see the run screen for the latter link, but you see the run screen of the former

**Comment by hellais** [comment]
I recall @lorenzoPrimi explaining to me something around this. Like that we basically have no ability to trigger some custom mavigations when the app is opened. Though probably what is happening is that the new overlay is shadowed by the old one.

@lorenzoPrimi does this make sense?

**Comment by lorenzoPrimi** [comment]
@hellais That was on Android. 
On iOS I guess as the view is already opened, the "launch and configure view" view method is not triggered. Will do more research

**Comment by hellais** [comment]
This happens to me on both iOS and Android

**Comment by lorenzoPrimi** [comment]
I tried to fix this checking if there is a window open in AppDelegate, if it's already opened I send the new parameters to the view. Seems to work fine.
