### ISSUE TITLE
XCode warning: UI API called on a background thread

### ISSUE THREAD

**Issue by lorenzoPrimi** [TheTorProject/ooniprobe-ios#134]
`Main Thread Checker: UI API called on a background thread: -[UIApplication applicationIconBadgeNumber]`

**Comment by lorenzoPrimi** [comment]
Thanks to the new xcode code diagnostics tools!
https://developer.apple.com/documentation/code_diagnostics/main_thread_checker?language=objc

**Comment by bassosimone** [comment]
@lorenzoPrimi it is not clear to me where you did fix this

**Comment by lorenzoPrimi** [comment]
I added all the dispatch_async(dispatch_get_main_queue(), ^{
When updating the badgeicon

**Comment by bassosimone** [comment]
Yes, sorry, I was confused because I assumed the merge was in master.
