### ISSUE TITLE
Max runtime is used when testing custom URIs

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooniprobe-ios#138]
Currently when I start something with the custom URI scheme, the maximum runtime of the test is followed. So if I have a very long list of URLs only some of them will get tested and not all of them (only until the timeout is reached).

Since the user is choosing to test all the sites in there, we should not respect the max runtime, but instead only consider that when web_connectivity is run with no arguments.

I think this is currently a blocker on releasing 1.2.2.

**Comment by bassosimone** [comment]
The fix for this would probably be to avoid setting `max_runtime` when using the custom URI scheme.
