### ISSUE TITLE
Description for IM tests

### ISSUE THREAD

**Issue by lorenzoPrimi** [TheTorProject/ooniprobe-ios#162]
I need a short test description for WhatsApp, Telegram and Facebook Messenger tests, before merging this PR : https://github.com/TheTorProject/ooniprobe-ios/pull/159
Ideally should be a short one row line.

**Comment by lorenzoPrimi** [comment]
@agrabeli @elioqoshi

**Comment by agrabeli** [comment]
@lorenzoPrimi you can use the following descriptions:

"whatsapp" = "Check if WhatsApp is blocked"';

"facebook_messenger" = "Check if Facebook Messenger is blocked";

"telegram" = "Check if Telegram is blocked";

Are these the type of short descriptions that you need?

**Comment by lorenzoPrimi** [comment]
great, submitting to transifex now

**Comment by hellais** [comment]
@lorenzoPrimi be sure to submit it to transifex using the script and after having committed it to a branch
