### ISSUE TITLE
What's new field in app store

### ISSUE THREAD

**Issue by lorenzoPrimi** [TheTorProject/ooniprobe-ios#163]
From this version on, it would be good to write a nice "what's new" paragraph instead of just a list of new features.
@agrabeli do you want to write it? 
What's new? We added the IM tests! whatsapp, telegram, facebook messenger!

**Comment by agrabeli** [comment]
@lorenzoPrimi sounds great! We could add the following:

New tests for measuring the blocking of WhatsApp, Facebook Messenger, and Telegram!

Run these tests to collect data confirming whether and how these apps are blocked by your ISP.
