### ISSUE TITLE
Truncated/invalid OONI Run links don't show an error

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooniprobe-ios#169]
When I tap on a OONI Run link that is truncated or invalid, the app opens up, but then doesn't show the OONI Run page, nor any error message.

It should instead show an error telling the user that the run link is invalid.

Here is a sample link:
```
https://run.ooni.io/nettest?tn=web_connectivity&ta=%7B%22urls%22%3A%5B%22http%3A%2F%2Fabrahadesta.wordpress.com%22%2C%22http%3A%2F%2Faljazeera.net%22%2C%22http%3A%2F%2Fam.wikipedia.org%22%2C%22http%3A%2F%2Fam.wikipedia.org%2Fwiki%2F%25E1%258B%258B%25E1%258A%2593%25E1%258B%258D_%25E1%258C%2588%25E1%258C%25BD%22%2C%22http%3A%2F%2Famharic.voanews.com%22%2C%22http%3A%2F%2Fancientgebts.org%22%2C%22http%3A%2F%2Fcarpediemethiopia.blogspot.com%22%2C%22http%3A%2F%2Fcitizenlab.org%22%2C%22https%3A%2F%2Fcitizenlab.org%2F2013%2F03%2Fyou-only-click-twice-finfishers-global-proliferation-2%2F%22%2C%22http%3A%2F%2Fcpj.org%22%2C%22http%3A%2F%2Fegoportal.blogspot.com%22%2C%22https%3A%2F%2Fendalk.wordpress.com%22%2C%22http%3A%2F%2Fenupfforethiopia.org%22%2C%22http%3A%2F%2Fethiomedia.com%22%2C%22http%3A%2F%2Fethiopianreview.com%22%2C%22http%3A%2F%2Fethiopiaonmymind.blogspot.com%22%2C%22http%3A%2F%2Fethiox.com%22%2C%22http%3A%2F%2Fethsat.com%22%2C%22http%3A%2F%2Ffacebook.com%22%2C%22https%3A%2F%2Ffaceboo 
```

**Comment by lorenzoPrimi** [comment]
@hellais what happens in Android with the same url?

**Comment by lorenzoPrimi** [comment]
The problem here is not the truncated url but the "mv" missing.
Adding "mv" param and trying again

**Comment by lorenzoPrimi** [comment]
a truncated url causes the app to crash because can't be converted in Array, will be fixed soon. Waiting for a comment on what to do when mv is missing

**Comment by hellais** [comment]
> @hellais what happens in Android with the same url?

I don't have an Android to test this on at the moment.

> The problem here is not the truncated url but the "mv" missing.

Ok. If the `mv` parameter is missing, then the app should say that is what is missing. It should not just open the app and not show anything related to OONI Run.

**Comment by lorenzoPrimi** [comment]
Ok so similar to invalid_param : test_name, I can show a popup invalid_param : test_arguments or missing_param : mv
