### ISSUE TITLE
OONI Probe 2.0: keep the screen on while running tests?

### ISSUE THREAD

**Issue by lorenzoPrimi** [TheTorProject/ooniprobe-ios#172]
As a test can be a long running process maybe we should keep the screen on during the process, 
or at least have this option in the settings.

Otherwise the user would have to unlock the phone after the test is finished.

**Comment by hellais** [comment]
Yes I agree. Is this something that is "officially" supported by the iOS SDK?

**Comment by lorenzoPrimi** [comment]
Yes, I use the same technique on BetStatus
`        [[UIApplication sharedApplication] setIdleTimerDisabled:YES];
`

https://developer.apple.com/documentation/uikit/uiapplication/1623070-idletimerdisabled

**Comment by lorenzoPrimi** [comment]
Do you think is better to keep the screen on during the test or let the user decide?

**Comment by hellais** [comment]
> Do you think is better to keep the screen on during the test or let the user decide?

I would make it a configurable option that is enabled by default (the screen doesn't timeout by default).
