### ISSUE TITLE
Address feedback from UX review

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooniprobe-ios#47]
# Overall
- Switch to a light background theme
# First start
- [ ] Move the next button into the bottom
## Step 2

Suggestions to make it understand that it's scrollable:

a. [ ] Transparency of the last lines of texts fading

b. [ ] Scrollbar always visible
- [ ] Potentially reduce the amount of text for mobile
## Step 3
- [ ] Use the default widgets for the selector and options
## Step 4
- [ ] Use the default widgets for the selector and options
# Main page
- [ ] Info buttons should be less bright
- [ ] Make the measurement results highlighted when you click on it
- [ ] When you click on the actual measurement it opens the log
- [ ] Give some visual cue that some have multiple results and some don't (drop log button)
# Settings page
- [ ] Reduce the amount of text in the settings options
- [ ] Make buttons 
# Multiple entry measurements
- [ ] Add back button when I first open it
- [ ] Remove word input
- [ ] Order them by top level domain and put the http and https version next to each other
- [ ] Add title results by domain
- [ ] Add button to "disable/enable errors"
- [ ] In the individual page result page, the back button points to the multiple entry page
# Measurement result page
- [ ] Drop the title "Test Results"
- [ ] Make the date go on the next line
- [ ] Remove measurement from the page

cc @scouttle

**Comment by hellais** [comment]
xref: https://github.com/measurement-kit/netprobe-android/issues/16

**Comment by willscott** [comment]
A couple more UI observations:

[ ] At the end of the consent flow, the button saying 'I'm all "set"' doesn't need quotes around "set"
[ ] Ndt test is a weird name for humans "Speed Test" or "Network Diagnostic Test" might be better
[ ] The hamburger menu / sidebar doesn't close by tapping in the partially obscured main pane. The specific menu button needs to be clicked again to close it, which isn't the standard ios interaction
[ ] In the past tests / results page, the whole item clicks to view results, the 'View' button is maybe not needed?

**Comment by lorenzoPrimi** [comment]
I guess it's not the most appropriate thread, I should have close this ages ago 😅 
@willscott thanks for your suggestion, I agree on the first two. 
Asking @bassosimone comments about the second one.

About the third, you can close the menu by sliding it or tapping in the menu button, either when the menu is closed or open. I don't think it's a but at all.

In the past test ndt, I made all the row tappable, not only the button, as we didn't have any action to assign to the row, do you think I should remove it? @hellais

**Comment by bassosimone** [comment]
>> Ndt test is a weird name for humans "Speed Test" or "Network Diagnostic Test" might be better
> Asking @bassosimone comments about the second one.

I agree with @willscott. I am a bit reluctant re: calling it "Speed Test" because that automatically draws a comparison with OOKLA's SpeedTest and the methodology of NDT is different. NDT was originally Network Diagnostic Tool. Now, MK implements just the performance subset of the NDT protocol and is not a tool, so, perhaps I'd say Network Performance Test and I would say in the description &mdash; it's probably already like this &mdash; that it's based on NDT. Ok?

**Comment by lorenzoPrimi** [comment]
With @hellais we agreed to rename in "NDT Speed Test" instead of "Ndt Test"

**Comment by willscott** [comment]
@lorenzoPrimi Regarding menu sliding: I see what you mean.
What i tried to do but didn't work was grab the white area of the main pane when the menu was open to 'pull it closed'. Only the top menu bar allows dragging, but when the menu is open, I expect the full obscured view to be draggable.

**Comment by lorenzoPrimi** [comment]
Try the new menu, do you like it?

**Comment by willscott** [comment]
New Menu is great :+1:
