### ISSUE TITLE
First App Store release

### ISSUE THREAD

**Issue by lorenzoPrimi** [TheTorProject/ooniprobe-ios#51]
I'm opening this issue as we are close to release the app in the App Store and I want to keep track of anything that is missing, bugged or should be addressed in this first version.

**Comment by bassosimone** [comment]
Thanks!

**Comment by lorenzoPrimi** [comment]
So far, I think there are only two issue to be addressed before the release:

- How to download and update url list (for web connectivity test)
- Merge the tree/mk-v0.4 branch
