### ISSUE TITLE
Failed "NDT Speed Test" never renders

### ISSUE THREAD

**Issue by willscott** [TheTorProject/ooniprobe-ios#72]
The NDT Speed test times out. when clicking the past result, it just renders as "Loading"

The log is
```
ip_lookup() failed: error code 1004
Not knowing user_ip means we cannot attempt to scrub it from the report
Results collector: https://b.collector.ooni.io
Opening report; please be patient...
cannot access entry["test_s2c"][0]: missing entry
cannot access entry["test_c2s"][0]: missing entry
cannot write entry
ooni_reporter: missing report ID
```

**Comment by bassosimone** [comment]
So, the reason why the test *fails* here is probably the same that I discussed in https://github.com/measurement-kit/ooniprobe-ios/issues/61#issuecomment-277219436.

The reason why the UI does not show anything I believe it is a *separate* problem triggered by the report file not containing all the expected fields.

**Comment by lorenzoPrimi** [comment]
@bassosimone can this be closed?

**Comment by willscott** [comment]
I think this is not a bug in ooniprobe-ios, but rather in wui, which should show an error when it fails to render a view rather than just sticking on "Loading"

**Comment by hellais** [comment]
Does anybody have a sample of a JSON report that is triggering this error? 

I believe https://github.com/TheTorProject/ooni-wui/pull/29 should fix it, but I would like to test it.

**Comment by hellais** [comment]
This is fixed.
