### ISSUE TITLE
Improve http-invalid-request-line logs

### ISSUE THREAD

**Issue by bassosimone** [TheTorProject/ooniprobe-ios#80]
In my phone, the last line or so of the logs is truncated when the logs span less than one screen, as shown by the following screenshot for http-invalid-request-line logs:

![index](https://cloud.githubusercontent.com/assets/337298/22667481/3792c448-ecbd-11e6-9dea-e15785ec8e99.jpg)

**Comment by hellais** [comment]
This also happens to me, but for the http header field manipulation test:

![image uploaded from ios 4](https://user-images.githubusercontent.com/424620/30884810-49acc254-a311-11e7-929b-64dde5b703c3.jpg)

**Comment by bassosimone** [comment]
Should be fixed in v0.7.5.
