### ISSUE TITLE
Purge tests

### ISSUE THREAD

**Issue by mrphs** [TheTorProject/ooniprobe-ios#85]
There should be a button at the bottom of all the test results to purge all the tests and logs from the phone. If you had been running daily tests for a while, it's a lot of test to remove one by one.

**Comment by lorenzoPrimi** [comment]
We need an icon or a better text. @hellais 
![simulator screen shot 14 feb 2017 12 26 18](https://cloud.githubusercontent.com/assets/1616097/22927313/d596801e-f2b0-11e6-8f9f-b895f521b615.png)

**Comment by hellais** [comment]
This is implemented now.
