### ISSUE TITLE
Icons in the setting menu

### ISSUE THREAD

**Issue by mrphs** [TheTorProject/ooniprobe-ios#86]
1- uploading data needs a better logo and perhaps a better phrase. Maybe "uploading data to the pool" or something like that would be a better one. The current logo is globally and generally used for sharing things on social media, which is very different with the meaning of this item.

2- The icons for "include network info" and "include country name" should be swapped.

**Comment by lorenzoPrimi** [comment]
Waiting for @hellais input on 1

**Comment by hellais** [comment]
I fully agree for 2., I am a bit uncertain about 1.

We could I guess rename it to "Upload measurements" and use an icon like the following: http://fontawesome.io/icon/upload/.

@agrabeli may also have some comments here.

**Comment by lorenzoPrimi** [comment]
I'm ready for this @agrabeli what do you think?

**Comment by mrphs** [comment]
@hellais yeah I think both the icon and new phrase make it more clear what it does.

**Comment by hellais** [comment]
Has this been implemented?

**Comment by lorenzoPrimi** [comment]
Yes
