### ISSUE TITLE
permission to add labels

### ISSUE THREAD

**Issue by mrphs** [TheTorProject/ooniprobe-ios#87]
Seems like I can only add or use labels in certain repos and not this one. It would be nice and help in organizing if all members are able to do it.

otherwise, please create a "usability" label. I've incoming tickets ;)

**Comment by bassosimone** [comment]
@mrphs I don't know exactly how to give the permission to add labels. For starters, anyway, I have created the usability labels. (And, thanks!, those are all very important and great tickets 👍 )

**Comment by mrphs** [comment]
Thanks! but I still can't use them. Maybe @hellais knows how. And thanks for your appreciation. I've more. Looking forward to a hangout session to discuss the rest.

**Comment by bassosimone** [comment]
Ah, yes, you also needed to be into a specific group. Can you try again?

**Comment by mrphs** [comment]
same

**Comment by bassosimone** [comment]
It says [in here that it is not possible to give fine-grained permissions like that](https://github.com/isaacs/github/issues/311), dammit. I'd say we proceed that you open issues and indicate if you want specific tags to be applied, and we follow suit.

**Comment by bassosimone** [comment]
I think we can close this issue.
