### ISSUE TITLE
Branding: simplify the name of the app

### ISSUE THREAD

**Issue by mrphs** [TheTorProject/ooniprobe-ios#88]
"ooniprobe" is too long to type and doesn't mean anything to people unfamiliar with OONI. The shorter and easier to remember the name of the app, the better. More people can find and understand what is it good for.

**Comment by mrphs** [comment]
I think it's also important to keep the description short and right to the point. It's currently probably too long for anyone to really follow and understand why they should get this app.

**Comment by bassosimone** [comment]
I don't have a super strong opinion on this. I guess the rationale of calling it `ooniprobe` is that the python software is also called `ooniprobe`, so it's consistent. But it is clearly true that `ooni` is a shorter name and one can also decide to rename *all* applications as `ooni`. I guess, in the end, this is a question that @hellais is the person better suited to answer.

**Comment by elioqoshi** [comment]
I had this discussion today with @hellais and to give a bit of context, we have several user facing projects right now at OONI (they are written similar in the logos)

OONI Explorer
OONI Measurements
OONI Proteus
OONI Run
ooniprobe

As you can see from the latter, it would make more sense to call it OONI Probe.
Also, as OONI is more like a set of tools which have the same goal but do different things, it would rather make sense to call OONI the whole project and/or tools and Probe/ Explorer / etc the specific tools in situations which require referring to them. What do you think?

**Comment by hellais** [comment]
So I've though more about this and looked also at examples of branding of apps in mobile app stores ("Google Allo", "Foursquare Swarm", "Firefox Focus", "Amazon Shopping", "Runtastic Running & Fitness", the list goes on) and I have come to the conclusion that I think "OONI Probe" is the best way to proceed in renaming.

Second to this we could also maybe make the name be "OONIProbe", but I think that condensing the two words together just adds confusion.

I suggest we do this re-naming revamp together with the grand redesign of the mobile app.

👍 👎 ?

**Comment by agrabeli** [comment]
@elioqoshi What you're suggesting makes sense. 

I think I would prefer to keep `ooniprobe` because we have been using it so extensively, that it just feels weird to rename it to anything else. Also, all of our copy (on the website, apps, web UI, blogs, reports, etc.) has always included "ooniprobe", which is also what our community members are more familiar with. 

That said, I don't think it's useful for me to bike-shed on this, and what you're suggesting makes sense. So :+1: from me. :)

**Comment by hellais** [comment]
This is now implemented.
