### ISSUE TITLE
Changing color used to indicate anomalies?

### ISSUE THREAD

**Issue by bassosimone** [TheTorProject/ooniprobe-ios#97]
I was discussing with a user that submitted a long and informative bug report and he was commenting that red is, in his opinion, too aggressive for what we consider *anomalies*, as red is usually used to indicate very-bad-things. He maintains that perhaps yellow or pink would better convey the meaning of "look closely at this".

xref: https://github.com/TheTorProject/ooniprobe-android/issues/67

**Comment by lorenzoPrimi** [comment]
@bassosimone

**Comment by bassosimone** [comment]
We can close this as well !
